#!/bin/bash

# Entry point for the install scripts

echo "Installing Homebrew"
if test ! $(which brew); then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi
brew update
echo "Install Homebrew Packages"
brew tap homebrew/bundle
pushd homebrew
brew bundle
popd
