#!/bin/bash

# Entry point for the install scripts

echo "Installing Homebrew"
if test ! $(which brew); then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi
brew update

# Install mackup first
echo "Install mackup and set up config"
brew install mackup

if test -f "$FILE"; then
    echo "$FILE already exists."
else
cat <<EOF
[storage]
engine = icloud
EOF > $HOME/.mackup.cfg
fi

echo "Install Homebrew Packages"
brew tap homebrew/bundle
pushd homebrew
brew bundle
popd
