#!/bin/bash

# Entry point for the install scripts

echo "Asking for you to authenticate to sudo"
sudo -l >/dev/null

echo "Installing Homebrew"
if test ! $(which brew); then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi
brew update

# Install mackup first
echo "Install mackup and set up config"
brew install mackup

if test -f "HOME/.mackup.cfg"; then
    echo "$HOME/.mackup.cfg already exists."
else
  printf "[storage]\nengine = icloud\n" > $HOME/.mackup.cfg
fi

echo "Install Homebrew Packages"
brew tap homebrew/bundle
pushd homebrew
brew bundle
popd
